# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from alter.memory.v1 import memory_pb2 as alter_dot_memory_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in alter/memory/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeWriteback = channel.unary_unary(
                '/alter.memory.v1.MemoryService/ProposeWriteback',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.ProposeWritebackRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.ProposeWritebackResponse.FromString,
                _registered_method=True)
        self.PromoteMemory = channel.unary_unary(
                '/alter.memory.v1.MemoryService/PromoteMemory',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.PromoteMemoryRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.PromoteMemoryResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/alter.memory.v1.MemoryService/UpdatePolicy',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.GetMemorySettings = channel.unary_unary(
                '/alter.memory.v1.MemoryService/GetMemorySettings',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.GetMemorySettingsRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.GetMemorySettingsResponse.FromString,
                _registered_method=True)
        self.UpdateMemorySettings = channel.unary_unary(
                '/alter.memory.v1.MemoryService/UpdateMemorySettings',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdateMemorySettingsRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdateMemorySettingsResponse.FromString,
                _registered_method=True)
        self.MemoryAccess = channel.unary_unary(
                '/alter.memory.v1.MemoryService/MemoryAccess',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.MemoryAccessRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.MemoryAccessResponse.FromString,
                _registered_method=True)
        self.RecallChat = channel.unary_unary(
                '/alter.memory.v1.MemoryService/RecallChat',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallChatRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallChatResponse.FromString,
                _registered_method=True)
        self.RecallWorkflow = channel.unary_unary(
                '/alter.memory.v1.MemoryService/RecallWorkflow',
                request_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallWorkflowRequest.SerializeToString,
                response_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallWorkflowResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProposeWriteback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemorySettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemorySettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecallChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecallWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeWriteback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeWriteback,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.ProposeWritebackRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.ProposeWritebackResponse.SerializeToString,
            ),
            'PromoteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteMemory,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.PromoteMemoryRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.PromoteMemoryResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'GetMemorySettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemorySettings,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.GetMemorySettingsRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.GetMemorySettingsResponse.SerializeToString,
            ),
            'UpdateMemorySettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemorySettings,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdateMemorySettingsRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.UpdateMemorySettingsResponse.SerializeToString,
            ),
            'MemoryAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryAccess,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.MemoryAccessRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.MemoryAccessResponse.SerializeToString,
            ),
            'RecallChat': grpc.unary_unary_rpc_method_handler(
                    servicer.RecallChat,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallChatRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallChatResponse.SerializeToString,
            ),
            'RecallWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.RecallWorkflow,
                    request_deserializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallWorkflowRequest.FromString,
                    response_serializer=alter_dot_memory_dot_v1_dot_memory__pb2.RecallWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alter.memory.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alter.memory.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProposeWriteback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/ProposeWriteback',
            alter_dot_memory_dot_v1_dot_memory__pb2.ProposeWritebackRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.ProposeWritebackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/PromoteMemory',
            alter_dot_memory_dot_v1_dot_memory__pb2.PromoteMemoryRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.PromoteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/UpdatePolicy',
            alter_dot_memory_dot_v1_dot_memory__pb2.UpdatePolicyRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemorySettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/GetMemorySettings',
            alter_dot_memory_dot_v1_dot_memory__pb2.GetMemorySettingsRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.GetMemorySettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemorySettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/UpdateMemorySettings',
            alter_dot_memory_dot_v1_dot_memory__pb2.UpdateMemorySettingsRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.UpdateMemorySettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/MemoryAccess',
            alter_dot_memory_dot_v1_dot_memory__pb2.MemoryAccessRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.MemoryAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecallChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/RecallChat',
            alter_dot_memory_dot_v1_dot_memory__pb2.RecallChatRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.RecallChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecallWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alter.memory.v1.MemoryService/RecallWorkflow',
            alter_dot_memory_dot_v1_dot_memory__pb2.RecallWorkflowRequest.SerializeToString,
            alter_dot_memory_dot_v1_dot_memory__pb2.RecallWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
