import {describe,expect,it} from "vitest";
import {StaffBillingActionRequestSchema,StaffBillingIssuesSchema,StaffBillingOperationSchema,RazorpayRecoveryUrlSchema} from "./staff-billing-operations";
const tenant="00000000-0000-7000-8000-0000000000a1",base={id:"bop_00000000-0000-7000-8000-000000000001",tenant_id:tenant,action:"grant_credits",actor_ref:"stf_billing",reason:"Grant verified runs",created_at:"2026-10-05T00:00:00.000Z",etag:`"billing-${tenant}-2"`,runs:3,credits:6,delivery:"pending",recovery_url:null,subscription_ref:"sub_recorded",invoice_ref:null};
describe("staff billing operations boundaries",()=>{
 it("accepts complete attributed pending and delivered run-credit grants",()=>{expect(StaffBillingOperationSchema.parse(base).credits).toBe(6);expect(StaffBillingOperationSchema.parse({...base,delivery:"delivered"}).delivery).toBe("delivered");});
 it("rejects malformed grants, actor injection, empty reasons and noninteger runs",()=>{for(const request of [{action:"grant_credits",runs:0,reason:"Valid"},{action:"grant_credits",runs:1.1,reason:"Valid"},{action:"grant_credits",runs:1,reason:""},{action:"grant_credits",runs:1,reason:"Valid",actor_ref:"stf_other"},{action:"retry",reason:"x".repeat(1001)}])expect(StaffBillingActionRequestSchema.safeParse(request).success).toBe(false);});
 it("rejects another subject's revision and inconsistent operation evidence",()=>{for(const patch of [{etag:'"billing-00000000-0000-7000-8000-0000000000b1-2"'},{delivery:null},{runs:null},{credits:null},{action:"retry"},{action:"resolve",runs:null,credits:null,delivery:null}])expect(StaffBillingOperationSchema.safeParse({...base,...patch}).success).toBe(false);});
 it("rejects outside, deceptive, insecure and credential-bearing recovery links",()=>{for(const value of ["http://rzp.io/path","https://rzp.io.evil.test/path","https://user:pass@rzp.io/path","https://rzp.io:444/path","https://rzp.io/","https://rzp.io/path#fragment"])expect(RazorpayRecoveryUrlSchema.safeParse(value).success).toBe(false);expect(RazorpayRecoveryUrlSchema.parse("https://rzp.io/rzp/actual")).toBeTruthy();});
 it("rejects duplicate or oversized issue lists and wrong tenant revisions",()=>{const row={tenant_id:tenant,tenant_name:"Recorded tenant",state:"grace",current_plan:"basic",first_failed_at:null,updated_at:"2026-10-05T00:00:00.000Z",etag:`"billing-${tenant}-1"`};expect(StaffBillingIssuesSchema.safeParse([row,row]).success).toBe(false);expect(StaffBillingIssuesSchema.safeParse(Array.from({length:501},()=>row)).success).toBe(false);expect(StaffBillingIssuesSchema.safeParse([{...row,etag:'"billing-00000000-0000-7000-8000-0000000000b1-1"'}]).success).toBe(false);});
});
