import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {billingAction,billingIssues,billingHistory} from "./live-admin-billing-ops";
const tenant="00000000-0000-7000-8000-0000000000a1",etag=`"billing-${tenant}-1"`,fetcher=vi.fn<typeof fetch>();
const operation={id:"bop_00000000-0000-7000-8000-000000000001",tenant_id:tenant,action:"grant_credits",actor_ref:"stf_billing",reason:"Actual reason",created_at:"2026-10-05T00:00:00.000Z",etag:`"billing-${tenant}-2"`,runs:3,credits:6,delivery:"pending",recovery_url:null,subscription_ref:null,invoice_ref:null};
beforeEach(()=>{fetcher.mockReset();vi.stubGlobal("fetch",fetcher)});afterEach(()=>vi.unstubAllGlobals());
describe("live staff billing HTTP boundary",()=>{
 it("sends exact displayed revision and full reason without browser actor attribution",async()=>{fetcher.mockResolvedValue(Response.json(operation));expect(await billingAction(tenant,etag,{action:"grant_credits",runs:3,reason:"Actual reason"})).toMatchObject({delivery:"pending",runs:3});const [url,init]=fetcher.mock.calls[0]!;expect(String(url)).toContain(`/issues/${tenant}/actions/grant-credits`);expect(new Headers(init?.headers).get("if-match")).toBe(etag);expect(JSON.parse(init!.body as string)).toEqual({runs:3,reason:"Actual reason"});expect(init?.credentials).toBe("include");});
 it("rejects malformed collections instead of converting provider failure to empty",async()=>{for(const payload of [{error:"busy"},[{tenant_id:tenant}]]){fetcher.mockResolvedValue(Response.json(payload));await expect(billingIssues()).rejects.toThrow();}fetcher.mockResolvedValue(Response.json([]));await expect(billingIssues()).resolves.toEqual([]);});
 it("rejects misbound and malformed operation acknowledgement",async()=>{for(const patch of [{tenant_id:"00000000-0000-7000-8000-0000000000b1"},{action:"resolve"},{delivery:null},{etag:undefined},{runs:4},{reason:"Other adjustment"}]){fetcher.mockResolvedValue(Response.json({...operation,...patch}));await expect(billingAction(tenant,etag,{action:"grant_credits",runs:3,reason:"Actual reason"})).rejects.toThrow();}});
 it("retains normal stale and provider errors, and parses bounded history",async()=>{fetcher.mockResolvedValue(Response.json({detail:"Billing issue changed"},{status:412}));await expect(billingAction(tenant,etag,{action:"retry",reason:"Actual reason"})).rejects.toThrow("Billing issue changed");fetcher.mockResolvedValue(Response.json([operation]));await expect(billingHistory(tenant)).resolves.toEqual([operation]);});
});
