import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {afterEach,beforeEach,describe,expect,it} from "vitest";
import {createBillingOpsNativeDriver} from "./testing/billing-ops-native-driver";
const database=process.env.DATABASE_URL;
describe.skipIf(!database)("staff billing ordinary PostgreSQL evidence",()=>{
 let d:Awaited<ReturnType<typeof createBillingOpsNativeDriver>>;
 beforeEach(async()=>{d=await createBillingOpsNativeDriver();},60000);afterEach(async()=>{await d?.close();},60000);
 const grant=async(reason="Actual attributed grant")=>d.service.apply(d.tenant,"stf_native_ops",{action:"grant_credits",runs:3,reason},await d.revision());
 it("persists attributed pending grant and independent tenant scope under ordinary FORCE RLS",async()=>{
  expect((await d.pool.query("SELECT rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user")).rows[0]).toEqual({rolsuper:false,rolbypassrls:false});const saved=await grant();expect(saved).toMatchObject({runs:3,credits:6,delivery:"pending",reason:"Actual attributed grant"});expect(await d.repository.history(d.other)).toEqual([]);
  expect((await d.pool.query("SELECT id FROM billing_admin_operations")).rowCount).toBe(0);await d.admin.query("SELECT set_config('app.current_tenant_id',$1,false)",[d.tenant]);expect((await d.admin.query("SELECT operation_id,credits,published_at FROM billing_admin_credit_deliveries")).rows).toEqual([{operation_id:saved.id,credits:6,published_at:null}]);
  expect((await d.admin.query("SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relnamespace=$1::regnamespace AND relname IN ('billing_admin_operations','billing_admin_credit_deliveries') AND relkind='r'",[d.schema])).rows.every(row=>row.relrowsecurity&&row.relforcerowsecurity)).toBe(true);
 });
 it("requires missing and exact locked revision, and gives one simultaneous contender success",async()=>{
  const input={action:"grant_credits",runs:1,reason:"Contender"};await expect(d.service.apply(d.tenant,"stf_native_ops",input,undefined)).rejects.toMatchObject({status:428});const revision=await d.revision();const responses=await Promise.allSettled([d.service.apply(d.tenant,"stf_native_ops",input,revision),d.service.apply(d.tenant,"stf_native_ops",input,revision)]);expect(responses.filter(row=>row.status==="fulfilled")).toHaveLength(1);expect((responses.find(row=>row.status==="rejected") as PromiseRejectedResult).reason).toMatchObject({status:412});
 });
 it("rolls back all local data, revision and access when mandatory audit is unavailable or malformed",async()=>{
  const revision=await d.revision();for(const mode of ["fail","invalid"] as const){d.auditState.mode=mode;await expect(grant()).rejects.toThrow();expect(await d.revision()).toBe(revision);expect(await d.repository.history(d.tenant)).toEqual([]);}d.auditState.mode="ok";
  d.providerState.status="active";d.auditState.mode="fail";await expect(d.service.apply(d.tenant,"stf_native_ops",{action:"resolve",reason:"Confirm paid recovery"},revision)).rejects.toThrow();expect(await d.revision()).toBe(revision);await d.admin.query("SELECT set_config('app.current_tenant_id',$1,false)",[d.tenant]);expect((await d.admin.query("SELECT access_state FROM entitlements WHERE tenant_id=$1 AND effective_to IS NULL",[d.tenant])).rows[0].access_state).toBe("grace");
 });
 it("cannot mutate immutable history, delivery quantity or another subject's records",async()=>{
  const saved=await grant(),tx=await d.pool.connect();try{await tx.query("BEGIN");await tx.query("SELECT set_config('app.current_tenant_id',$1,true)",[d.other]);expect((await tx.query("SELECT * FROM billing_admin_operations WHERE id=$1",[saved.id])).rowCount).toBe(0);expect((await tx.query("DELETE FROM billing_admin_operations WHERE id=$1",[saved.id])).rowCount).toBe(0);await tx.query("SELECT set_config('app.current_tenant_id',$1,true)",[d.tenant]);expect((await tx.query("UPDATE billing_admin_operations SET reason='Overwrite' WHERE id=$1",[saved.id])).rowCount).toBe(0);expect((await tx.query("DELETE FROM billing_admin_operations WHERE id=$1",[saved.id])).rowCount).toBe(0);}finally{await tx.query("ROLLBACK");tx.release();}
  await expect(d.admin.query("UPDATE billing_admin_operations SET reason='Overwrite' WHERE id=$1",[saved.id])).rejects.toThrow(/append-only/);await expect(d.admin.query("UPDATE billing_admin_credit_deliveries SET credits=99 WHERE operation_id=$1",[saved.id])).rejects.toThrow(/immutable/);
 });
 it("preserves existing billing rows on empty-history downgrade and reapplication, and refuses populated downgrade",async()=>{
  const down=readFileSync(resolve("apps/platform-api/src/db/migrations/rollback/0037_drop_admin_billing_operations.sql"),"utf8"),up=readFileSync(resolve("apps/platform-api/src/db/migrations/0037_admin_billing_operations.sql"),"utf8");for(const statement of down.split("--> statement-breakpoint"))if(statement.trim())await d.admin.query(statement);expect((await d.admin.query("SELECT subscription_ref FROM billing_profiles WHERE tenant_id=$1",[d.other])).rowCount).toBe(1);for(let index=0;index<2;index++)for(const statement of up.split("--> statement-breakpoint"))if(statement.trim())await d.admin.query(statement);await d.admin.query(`GRANT SELECT,INSERT,UPDATE,DELETE ON billing_admin_operations,billing_admin_credit_deliveries TO ${d.role}`);await grant();await expect(d.admin.query(down.split("--> statement-breakpoint")[0]!)).rejects.toThrow(/retained history/);
 });
 it("requires an active matching erasure manifest and preserves the unrelated tenant's credit history",async()=>{
  const first=await grant();const other=await d.service.apply(d.other,"stf_native_ops",{action:"grant_credits",runs:2,reason:"Unrelated grant"},await d.revision(d.other));
  const tx=await d.pool.connect();try{await tx.query("BEGIN");await tx.query("SELECT set_config('app.current_tenant_id',$1,true)",[d.tenant]);await expect(tx.query("SELECT erase_tenant_billing_admin_operations($1::uuid,$2)",[d.tenant,"del_00000000-0000-7000-8000-000000000001"])).rejects.toThrow(/no active erasure manifest/);}finally{await tx.query("ROLLBACK");tx.release();}
  await d.admin.query("INSERT INTO tenant_erasure_manifests(manifest_id,tenant_id) VALUES('del_00000000-0000-7000-8000-000000000001',$1)",[d.tenant]);await expect(d.pool.query("SELECT erase_tenant_billing_admin_operations($1::uuid,$2)",[d.tenant,"del_00000000-0000-7000-8000-000000000002"])).rejects.toThrow(/no active erasure manifest/);const removed=await d.pool.query("SELECT erase_tenant_billing_admin_operations($1::uuid,$2) AS n",[d.tenant,"del_00000000-0000-7000-8000-000000000001"]);expect(removed.rows[0].n).toBe(2);expect(await d.repository.history(d.tenant)).toEqual([]);expect((await d.repository.history(d.other)).map(row=>row.id)).toEqual([other.id]);expect(first.id).not.toBe(other.id);
 });
 it("rejects an older paid invoice when a newer invoice remains unpaid, wrong amounts and wrong currency",async()=>{
  d.providerState.status="active";const revision=await d.revision();for(const patch of [{latestUnpaid:true},{latestUnpaid:true,latestIssuedOffset:0},{amount:1},{invoiceCurrency:"USD"},{paidOffset:-10},{paidOffset:1000}]){Object.assign(d.providerState,{latestUnpaid:false,latestIssuedOffset:1,amount:11804,invoiceCurrency:"INR",paidOffset:1},patch);await expect(d.service.apply(d.tenant,"stf_native_ops",{action:"resolve",reason:"Actual provider evidence"},revision)).rejects.toMatchObject({status:409});expect(await d.revision()).toBe(revision);}
 });
 it("rechecks current billing roles inside the transaction and blocks role revocation while audit is pending",async()=>{
  const revision=await d.revision();await d.admin.query("UPDATE staff_users SET roles=ARRAY['staff_support'] WHERE id='stf_native_ops'");await expect(grant()).rejects.toMatchObject({status:403});expect(await d.revision()).toBe(revision);await d.admin.query("UPDATE staff_users SET roles=ARRAY['staff_billing_ops'] WHERE id='stf_native_ops'");
  let entered!:()=>void,release!:()=>void;const waiting=new Promise<void>(done=>{entered=done});d.auditState.pause=()=>{entered();return new Promise<void>(done=>{release=done})};const pending=grant();await waiting;const tx=await d.pool.connect();try{await tx.query("BEGIN");await tx.query("SET LOCAL lock_timeout='100ms'");await expect(tx.query("UPDATE staff_users SET deactivated_at=now() WHERE id='stf_native_ops'")).rejects.toMatchObject({code:"55P03"});}finally{await tx.query("ROLLBACK");tx.release();release();}await pending;
 });
 it("rejects missing plan pricing and bounds converted credit quantity before writing",async()=>{
  const definition=(await d.definitions.find("basic"))!;const revision=await d.revision();await d.definitions.upsert("basic",definition.limits,"stf_native_ops",{...definition.commercial!,creditsPerVerifiedRun:null},"Configuration unavailable");await expect(grant()).rejects.toMatchObject({status:503});expect(await d.revision()).toBe(revision);
  await d.definitions.upsert("basic",definition.limits,"stf_native_ops",{...definition.commercial!,creditsPerVerifiedRun:1_000_000_000},"Maximum configured price");await expect(d.service.apply(d.tenant,"stf_native_ops",{action:"grant_credits",runs:2,reason:"Quantity must be bounded"},revision)).rejects.toMatchObject({status:400});expect(await d.repository.history(d.tenant)).toEqual([]);
 });
 it("does not expose an uncommitted grant and serializes tenant deletion while awaiting audit",async()=>{
  let entered!:()=>void,release!:()=>void;const waiting=new Promise<void>(resolve=>{entered=resolve;});d.auditState.pause=()=>{entered();return new Promise<void>(resolve=>{release=resolve;});};const pending=grant();await waiting;expect(await d.repository.history(d.tenant)).toEqual([]);const tx=await d.pool.connect();try{await tx.query("BEGIN");await tx.query("SELECT set_config('app.current_tenant_id',$1,true)",[d.tenant]);await tx.query("SET LOCAL lock_timeout='100ms'");await expect(tx.query("UPDATE tenants SET deleted_at=now() WHERE id=$1",[d.tenant])).rejects.toMatchObject({code:"55P03"});}finally{await tx.query("ROLLBACK");tx.release();release();}expect((await pending).delivery).toBe("pending");
 });
});
