import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
const fixture=vi.hoisted(()=>({live:true}));vi.mock("@/api/http",async original=>({...await original<typeof import("@/api/http")>(),get isLiveApi(){return fixture.live}}));
import {BillingOpsQueue} from "./billing-ops";
const tenant="00000000-0000-7000-8000-0000000000a1",fetcher=vi.fn<typeof fetch>();let roles:string[],unavailable:boolean,empty:boolean,actionStatus:number,actions:Record<string,unknown>[];
const issue={tenant_id:tenant,tenant_name:"Actual tenant",state:"grace",current_plan:"basic",first_failed_at:"2026-10-05T00:00:00.000Z",updated_at:"2026-10-05T00:00:00.000Z",etag:`"billing-${tenant}-1"`};
beforeEach(()=>{fixture.live=true;roles=["staff_billing_ops"];unavailable=false;empty=false;actionStatus=201;actions=[];fetcher.mockReset();vi.stubGlobal("fetch",fetcher);fetcher.mockImplementation(async(url,init)=>{const path=new URL(String(url),"http://app.test").pathname;if(path==="/api/v1/admin/session")return Response.json({staffUserId:"stf_billing",email:"staff@test.test",roles});if(path.endsWith("/history"))return Response.json(actions);if(init?.method==="POST"){if(actionStatus!==201)return Response.json({detail:actionStatus===412?"Billing issue changed":"Mandatory audit unavailable"},{status:actionStatus});const body=JSON.parse(init.body as string),action=path.endsWith("grant-credits")?"grant_credits":path.endsWith("retry")?"retry":"resolve";const row={id:"bop_00000000-0000-7000-8000-000000000001",tenant_id:tenant,action,actor_ref:"stf_billing",reason:body.reason,created_at:"2026-10-05T00:01:00.000Z",etag:`"billing-${tenant}-2"`,runs:action==="grant_credits"?body.runs:null,credits:action==="grant_credits"?body.runs*2:null,delivery:action==="grant_credits"?"pending":null,recovery_url:action==="retry"?"https://rzp.io/rzp/actual-recovery":null,subscription_ref:"sub_actual",invoice_ref:action==="resolve"?"inv_actual":null};actions.unshift(row);return Response.json(row);}return unavailable?Response.json({detail:"Billing unavailable"},{status:503}):Response.json(empty?[]:[issue]);});});
afterEach(()=>{cleanup();vi.unstubAllGlobals()});function view(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><BillingOpsQueue/></QueryClientProvider>)}
describe("staff billing operations rendered live and demo",()=>{
 it("grants explicit verified runs with a human reason and revision, showing durable pending state",async()=>{view();fireEvent.click(await screen.findByRole("button",{name:"Grant run credits"}));const submit=screen.getByRole("button",{name:"Apply billing action"});expect(submit.hasAttribute("disabled")).toBe(true);fireEvent.change(screen.getByRole("textbox",{name:"Billing action reason"}),{target:{value:"Support adjustment for three runs"}});fireEvent.change(screen.getByRole("spinbutton",{name:"Verified runs"}),{target:{value:"3"}});await waitFor(()=>expect(submit.hasAttribute("disabled")).toBe(false));fireEvent.click(submit);expect((await screen.findByRole("status")).textContent).toContain("3 verified runs (6 credits). Delivery pending");const [,init]=fetcher.mock.calls.find(([,options])=>options?.method==="POST")!;expect(new Headers(init?.headers).get("if-match")).toBe(issue.etag);expect(JSON.parse(init!.body as string)).toEqual({runs:3,reason:"Support adjustment for three runs"});await screen.findByText(/grant_credits: Support adjustment/);});
 it("keeps retry as an actual hosted link and leaves payment unconfirmed",async()=>{view();fireEvent.click(await screen.findByRole("button",{name:"Retry payment"}));fireEvent.change(screen.getByRole("textbox",{name:"Billing action reason"}),{target:{value:"Customer will complete hosted recovery"}});fireEvent.click(screen.getByRole("button",{name:"Apply billing action"}));const link=await screen.findByRole("link",{name:"Open Razorpay recovery"});expect(link.getAttribute("href")).toBe("https://rzp.io/rzp/actual-recovery");expect(screen.getByRole("status").textContent).toContain("Payment remains unconfirmed");expect(screen.getByText("grace")).toBeTruthy();});
 it.each([412,500])("retains reason and quantity on failed operation %s",async code=>{actionStatus=code;view();fireEvent.click(await screen.findByRole("button",{name:"Grant run credits"}));fireEvent.change(screen.getByRole("textbox",{name:"Billing action reason"}),{target:{value:"Keep investigation reason"}});fireEvent.change(screen.getByRole("spinbutton",{name:"Verified runs"}),{target:{value:"4"}});const submit=screen.getByRole("button",{name:"Apply billing action"});await waitFor(()=>expect(submit.hasAttribute("disabled")).toBe(false));fireEvent.click(submit);await screen.findByRole("alert");expect((screen.getByRole("textbox",{name:"Billing action reason"}) as HTMLTextAreaElement).value).toBe("Keep investigation reason");expect((screen.getByRole("spinbutton",{name:"Verified runs"}) as HTMLInputElement).value).toBe("4");expect(screen.queryByRole("status")).toBeNull();});
 it("distinguishes unavailable from empty and permits reload",async()=>{unavailable=true;view();await screen.findByRole("alert");expect(screen.queryByText("No billing issues found.")).toBeNull();unavailable=false;empty=true;fireEvent.click(screen.getByRole("button",{name:"Reload billing issues"}));await screen.findByText("No billing issues found.");});
 it("withholds billing reads without current staff billing role",async()=>{roles=["staff_support"];view();await screen.findByText("Staff admin or billing operations role required.");expect(fetcher.mock.calls.some(([url])=>String(url).includes("/billing/issues"))).toBe(false);});
 it("uses explicit fictional demo records and performs no live requests",async()=>{fixture.live=false;view();await screen.findByText("Demo records — fictional billing, recovery links and credits.");expect(await screen.findAllByRole("button",{name:"Grant run credits"})).toHaveLength(2);expect(fetcher).not.toHaveBeenCalled();});
});
