import { type Permission, type UserRole } from "@/api/types"

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  owner: [
    "workspace.manage",
    "member.read",
    "member.invite",
    "member.update",
    "member.remove",
    "role.read",
    "role.manage",
    "workflow.read",
    "workflow.create",
    "workflow.update",
    "workflow.delete",
    "workflow.run",
    "project.read",
    "project.create",
    "run.read",
    "human_action.read",
    "human_action.claim",
    "human_action.decide",
    "human_action.annotate",
    "knowledge.read",
    "knowledge.manage",
    "connection.read",
    "connection.manage",
    "billing.read",
    "billing.manage",
    "admin.access",
    "conversation.read",
    "conversation.create",
    "trigger.read",
    "trigger.manage",
    "event.read",
    "event.replay",
    "webhook.read",
    "webhook.manage",
    "knowledge.test_retrieval",
    "knowledge.memory_manage",
    "credential.read",
    "credential.manage",
    "channel.read",
    "channel.manage",
    "data.export",
    "data.delete",
    "seller.access",
  ],
  admin: [
    "member.read",
    "member.invite",
    "member.update",
    "member.remove",
    "role.read",
    "workflow.read",
    "workflow.create",
    "workflow.update",
    "workflow.delete",
    "workflow.run",
    "project.read",
    "project.create",
    "run.read",
    "human_action.read",
    "human_action.claim",
    "human_action.decide",
    "human_action.annotate",
    "knowledge.read",
    "knowledge.manage",
    "connection.read",
    "connection.manage",
    "billing.read",
    "admin.access",
    "conversation.read",
    "conversation.create",
    "trigger.read",
    "trigger.manage",
    "event.read",
    "event.replay",
    "webhook.read",
    "webhook.manage",
    "knowledge.test_retrieval",
    "knowledge.memory_manage",
    "credential.read",
    "credential.manage",
    "channel.read",
    "channel.manage",
    "data.export",
    "data.delete",
  ],
  editor: [
    "billing.read",
    "member.read",
    "role.read",
    "workflow.read",
    "workflow.create",
    "workflow.update",
    "workflow.run",
    "project.read",
    "project.create",
    "run.read",
    "human_action.read",
    "knowledge.read",
    "connection.read",
    "conversation.read",
    "conversation.create",
    "trigger.read",
    "event.read",
    "webhook.read",
    "knowledge.test_retrieval",
    "credential.read",
    "channel.read",
  ],
  operator: [
    "member.read", "role.read", "workflow.read", "workflow.update", "workflow.run",
    "project.read", "run.read", "human_action.read", "human_action.claim", "human_action.decide",
    "knowledge.read", "connection.read", "conversation.read", "trigger.read", "event.read", "billing.read",
  ],
  approver: [
    "member.read", "role.read", "workflow.read", "project.read", "run.read", "human_action.read",
    "human_action.decide", "knowledge.read", "connection.read", "conversation.read", "event.read", "billing.read",
  ],
  viewer: [
    "member.read",
    "role.read",
    "workflow.read",
    "project.read",
    "run.read",
    "human_action.read",
    "knowledge.read",
    "connection.read",
    "conversation.read",
    "event.read",
    "credential.read",
    "channel.read",
  ],
}
